### ISSUE TITLE
Im running on a mac actually

### ISSUE THREAD

**Issue by rgee0** [rgee0/Test#2]
test test ttes

**Comment by rgee0** [comment]
Derek add label: fred

**Comment by rgee0** [comment]
Derek add label: fred

**Comment by rgee0** [comment]
Derek add label: fred

**Comment by rgee0** [comment]
Derek add label: hello

**Comment by rgee0** [comment]
Derek close: all done

**Comment by rgee0** [comment]
Derek open: changed my mind

**Comment by rgee0** [comment]
Derek reopen: changed my mind

**Comment by rgee0** [comment]
Derek reopen: changed my mind

**Comment by rgee0** [comment]
Derek reopen: changed my mind

**Comment by rgee0** [comment]
Derek reopen: changed my mind

**Comment by alexellis** [comment]
Interesting to see your "meta-comment" after the command.

Does `Derek close` / `Derek close issue` / `Derek close pr` / `Derek close this` / `Derek close pull request` work too?

**Comment by rgee0** [comment]
@alexellis `derek close` works on both issues and PRs.

The comment is also tracked in the logging to add context.

**Comment by rgee0** [comment]
Derek remove label: hello

**Comment by rgee0** [comment]
Derek set title: I like cheese

**Comment by alexellis** [comment]
Derek set title: I like making money

**Comment by alexellis** [comment]
Very cool Richard

**Comment by rgee0** [comment]
Derek set title: This title is splendid

**Comment by rgee0** [comment]
Derek lock

**Comment by rgee0** [comment]
Derek unlock

**Comment by alexellis** [comment]
Derek lock

**Comment by rgee0** [comment]
Derek assign: me

**Comment by rgee0** [comment]
Derek add label: fred

**Comment by rgee0** [comment]
Derek lock

**Comment by rgee0** [comment]
Derek set title: This thread should be locked

**Comment by rgee0** [comment]
Derek set title: This thread should be locked

**Comment by rgee0** [comment]
Derek remove label: fred

**Comment by rgee0** [comment]
Derek unlock

**Comment by rgee0** [comment]
Derek set title: Humpty Dumpty sat on a wall

**Comment by rgee0** [comment]
Derek set title: Humpty Dumpty sat on a wall

**Comment by rgee0** [comment]
Derek unlock

**Comment by rgee0** [comment]
Derek unlock

**Comment by rgee0** [comment]
Derek lock

**Comment by rgee0** [comment]
Derek lock

**Comment by rgee0** [comment]
Derek lock

**Comment by rgee0** [comment]
Derek lock

**Comment by rgee0** [comment]
Derek lock

**Comment by rgee0** [comment]
Derek lock

**Comment by rgee0** [comment]
Derek lock

**Comment by rgee0** [comment]
Derek lock

**Comment by rgee0** [comment]
Derek lock

**Comment by rgee0** [comment]
Derek lock

**Comment by rgee0** [comment]
Derek lock

**Comment by rgee0** [comment]
Derek lock

**Comment by rgee0** [comment]
Derek unlock

**Comment by rgee0** [comment]
Derek unlock

**Comment by rgee0** [comment]
Derek close

**Comment by rgee0** [comment]
Derek close

**Comment by rgee0** [comment]
Derek set title: Humpty Dumpty sat on a wall

**Comment by rgee0** [comment]
Derek close

**Comment by rgee0** [comment]
Derek reopen

**Comment by rgee0** [comment]
Derek set title: Its been a rather successful day

**Comment by alexellis** [comment]
Derek set title: It's been a rather rainy day

**Comment by alexellis** [comment]
@rgee0 is the bot running?

**Comment by rgee0** [comment]
Derek set title: It's been a rather rainy day

**Comment by rgee0** [comment]
Derek set title: It's been a rather rainy day

**Comment by rgee0** [comment]
Derek add label: test

**Comment by rgee0** [comment]
Derek add label: pi

**Comment by rgee0** [comment]
Derek remove label: test

**Comment by rgee0** [comment]
Derek remove label: hello

**Comment by rgee0** [comment]
Derek set title: I'm running on a Raspberry Pi

**Comment by rgee0** [comment]
Derek add label: fred

**Comment by alexellis** [comment]
Derek add label: are-you-though

**Comment by rgee0** [comment]
Derek set title: Im running on a mac actually
